---
name: 'build'

on:
  push:
    branches:
      - master

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Extra image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            BUILD_TYPE=extras
            FFMPEG=true
            IMAGE_TYPE=extras
            BASE_IMAGE=ubuntu:22.04
            GRPC_BASE_IMAGE=ubuntu:22.04
            GRPC_MAKEFLAGS=--jobs=4 --output-sync=target
            GRPC_VERSION=v1.65.0
            MAKEFLAGS=--jobs=4 --output-sync=target
          context: .
          file: ./Dockerfile
          cache-from: type=gha
          platforms: linux/amd64
          push: true
          tags: localai:extras
      - name: Build and push AIO image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            BASE_IMAGE=jiangxianfu/localai:extra
            MAKEFLAGS=--jobs=4 --output-sync=target
          context: .
          file: ./Dockerfile.aio
          platforms: linux/amd64
          push: true
          tags: localai:aio
