---
name: 'build'

on:
  push:
    branches:
      - master

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Build and push Extra image
        id: build_extra
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            BUILD_TYPE=extras
            FFMPEG=true
            IMAGE_TYPE=extras
            BASE_IMAGE=ubuntu:22.04
            GRPC_BASE_IMAGE=ubuntu:22.04
            GRPC_MAKEFLAGS=--jobs=4 --output-sync=target
            GRPC_VERSION=v1.65.0
            MAKEFLAGS=--jobs=4 --output-sync=target
          context: .
          file: ./Dockerfile
          cache-from: type=gha
          platforms: linux/amd64
          push: false
          tags: localai:extras
      - name: Build and push AIO image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            BASE_IMAGE=${{ steps.build_extra.outputs.image }}
            MAKEFLAGS=--jobs=4 --output-sync=target
          context: .
          file: ./Dockerfile.aio
          platforms: linux/amd64
          push: false
          tags: localai:aio
